var GAME_LEVELS = [
  ["                                             yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "                                                                           x!!!!",
   "                                                                            xx!!",
   "                                                                             x!!",
   "                                                                   o          x!",
   "                                                                              x!",
   "                              s                                   xxx         x!",
   "                                                            xx   xx!xx       xx!",
   "                       x x    xvvvx!o o                          x!!!x  y oyx!!!",
   "                       x x         !                             x!!!x  yo y!!!!",
   "xxx                    x x         xxxx            x             xvxvx  y oy!!!!",
   "!!!! o !!              xox                                              yo yxx!!",
   "!xxxxxxxxx             x x                    x                              x!!",
   "!xx                  j x x                                                   xx!",
   "!!x                  xxx xxx             x                                   xx!",
   "!!x  s        o                                                          oo  x!!",
   "!xx  @                                               x           xxxxx       x!!",
   "!xxxxxxxxx         xxxxxxxxxxxx   xxxxxxxx!!!xxx           xxxxxxx!!!xxxxxxxxx!!",
   "!!!!!!!!!x    x    x!!!!!!!!!!x   x!!!!!!!!!!!!x           x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                    x!!!x",
   "x!!!!!!xxx            xxxxx!!xxxxxxx!!!!!!!!xxxxx!!!!!xxx                                                     xx!x",
   "x!!!xxx                    xxx      xx!!!!!xx    xxxvxx                                                         xx",
   "xxxx                                  xvxvx                                                       xxxxxxxxx      x",
   "xx                                                                     o                         xxxx            x",
   "x                                                                                               xx!!xx           x",
   "x o               o                                                                         xxxxxx!!!xxxx   o   xx",
   "x                                                                 xxxxxxxxxxxxxx           xx   xx!!!!!!!x     xxx",
   "x                                                               xxx            xxx        xx    xxxxxxxx!xxxxxxxxx",
   "xx                                                             xx                xxxxxxxxxxx    xxxx   xvx    xxxx",
   "xxx    x                  xxx                                 xx                                yxx             xx",
   "xx     x                                                     xx                          o      yxx              x",
   "x      x                                                   xxx              xxxxx               yx           o   x",
   "x      xx        xxx                                      xx              xxx   xxxxxx       xxxxx               x",
   "x      xx                                            xxxxxx           xxxxx          xxxxxxxxx                   x",
   "x      xxx                                    o    xxxxx                                                         x",
   "x      xxx                                       xxxxxx                                                     xxxxxx",
   "xx     xx                                       xxxxxxx   o                                                       ",
   "xxx   xxx                                       xxxxxxxx                                                          ",
   "xxxxxxxxxxx                                    xxxxxxxxxxxxxxxxxxxxxxxxx                              xx          ",
   "xxxx  xx!!!x              xxxx        o      xxx                       xxx                                        ",
   "xx    x!!!!xx   xxxx     x!!!xxxx           xx                           xxxx              xxx                    ",
   "x     xx!!!!!xxxx!!!xxxxxx!!!!!!!x        xxx               o                                                     ",
   "x      x!!!!!!!!!!!!!!!!!!!!!!!!!!x     xxx                                                                       ",
   "x      xxxxxxxxxxxvxxxxxxxxxxxvxxxxxxxxxxx          xxx x x x x x x x                                             ",
   "x                                                  x!!!!!!!!!!!!!!!!!x                                          j ",
   "x s          o                                   xx!!!!!!!!!!!!!!!!!!x          xxx            o               xxx",
   "x @                                             x!!!!!!!!!!!!!!!!!!!!!x        xxxxx    =          =          xxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                       y                                                            y                         ",
   "                        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "           !         s                                                                         !              ",
   "           x                               o                   o                               x              ",
   "           xxx     xxx                                                               xxx  o   xxx              ",
   "           x         xxxxx      xxxx     xxxx      xxxx      xxxx      xxxx       xxxx v     v x              ",
   "           x    o    xxxxx!!!!xxxxxx!!!!xxxxxx!!!!xxxxxx!!!!xxxxxx!!!!xxxxxx!!!!xxxxxx         x              ",
   "           x         xxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxx         x              ",
   "           x    x    x                         vv        vv                          x         x              ",
   "        !  x         x  !                                                         !  x         x  !           ",
   "        x  x         x  x                                                         x  x         x  x           ",
   "        xxxx=       =xxxx                                                         xxxx         xxxx           ",
   "        x               x                                                         x  v         v  x           ",
   "        x               x               o                        o                x               x           ",
   "        x               x                                                         x               x           ",
   "        x               x              xxxx                    xxxx               x               x           ",
   "        x      xxx      x                                                         x               x           ",
   "        x               x                                                         x               x           ",
   "        x=             =x                                                         x               x           ",
   "     !  x               x  !                                                   !  x               x  !        ",
   "     x  x               x  x                                                   x  x               x  x        ",
   "     xxxxxxx    o    xxxxxxx  =                     ==                      =  xxxxxxx    o    xxxxxxx        ",
   "     x                     x                                                   x     v         v     x        ",
   "     x                     x                                                   x                     x        ",
   "     x                     x                                                   x                     x        ",
   "     x=                   =x                     xxxxxxxx                      x                     x        ",
   "     x                     x                                                   x                     x        ",
   "  !  x                     x  !                                             !  x                     x  !     ",
   "  x  x                     x  x                                             x  x                     x  x     ",
   "  xxxx         xxx         xxxx                                             xxxx                     xxxx     ",
   "  x                           x        xxx           o          xxx         x  v                     v  x     ",
   "  x                           x                                             x                           x     ",
   "  x                           x                                             x             o             x     ",
   "  x=                         =x                     ==                      x                           x     ",
   "  x                           x                                             x                           x     ",
   "  x      xxx         xxx      x                  xxxxxxxx                   x                           x     ",
   "  x             o             x                                             x                           x     ",
   "  x                           x                                             x                           x     ",
   "  x                           x        =                           =        x                           x     ",
   "  x             j             x                      j                                                  x     ",
   " !x=            @            =x!                     o                                                  x!    ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xx                                                                              ",
   "              x!!!!!!!!!!!!!!!!xxxxxx       s                                                                 ",
   "               xxxxxxxxxxx!!!!!!!!!!xxxxxx                                                                    ",
   "       o                xxxxxxxxx!!!!!!!!xxxxxx       o                        y     y     y     y       o    ",
   "       x                       xxxxxxx!!!!!!!!xxxxxx                          yxy x yxy x yxy x yxy x   ooo   ",
   "o                                    xxxxxx!!!!!!!!xxxx         x     x    x   y     y     y     y   x   o    ",
   "x                                         xxxxxx!!!!!v!xx                                            xxxxxxxxx",
   "                                               xxxxx! v!!x                                                 xxx",
   "                                                   xx  v!xx                                                  x",
   "                                                    x   vvxxxxxx                                              ",
   "xxx                   xx                            x    vvvvvvvxxxxxxxxxxxx                                  ",
   "   =                xxxxx   xxxxxxx                 x                      xxxx                               ",
   "           xxxxxxxxxxxxxxxxxx    xxxxxxx           xx                         xxx                             ",
   "           xxxx                        xxxxxx       xx!!!!                    xxxxxxxxx                       ",
   "          xxxx                              xxx     xxx!!!!!!!!                       xxxx    s               ",
   "          xxxx                                xxx     xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                   ",
   "    xxxxxxx                                    xx    xxxx!!!!!!!xxxx!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx           ",
   "       s                                        x o  xxxxx!!!!!x    vxxxxxxxvxxxxxxx!!!!!!!!!!!!!!x           ",
   "                                                x    xxxx!!!!!x                    xvxxxxxxxxxxxxv            ",
   "xxxxxxxxxxxxxxxxx                               x    xxx!!!!!x                                                ",
   "xxxxxxxxxxxxxxxx                                x o  x!!!!!!!x         o                                      ",
   "xxxxxxxxxxxxxx                                  x    x!!!!!!!x    j                                           ",
   "xxxxxxxxxxx                  xx                xx    x!!!!!!!x    xx                                          ",
   "xxxxx                                         xx     x!!!!!!v                                               xx",
   "                                              x      x!!!!!x           xx                                     ",
   "                                     o     j xx     xx!!!!x                                                   ",
   "                   xx                      xxxx     xx!!!x                      xx                            ",
   "                                     x      xxx    xxx!xx                                                     ",
   "             xx                              xxx     xvx                                 xx                   ",
   "                            xx                xx                                                              ",
   "   s   xx                                     xxx                                                  o          ",
   "   @                                         xxxxx                                                            ",
   "xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                    o                              o       ",
   "x         o         o   o   oo  o    o     o         o   o   o  o   o       ",
   "x          o   o   o    o   o o o    o      o   o   o    o   oo o   o       ",
   "x           o o o o     o   o  oo            o o o o     o   o oo           ",
   "x            o   o      o   o   o    o        o   o      o   o  o   o       ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x                                                                           ",
   "x   s                 j       s         j     s     j                      y",
   "x   @                                                                      y",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
